### ISSUE TITLE
Remoção de um valor do AnnotatedTreeNode

### ISSUE THREAD

**Issue by rafaelmacielrsm** [20152DIE99/Compilador#1]
Quando estivermos resolvendo uma Expressão do tipo:

> expr -> expr (ADD|SUB) expr # AddSub

Já podemos retirar o valor das expr do hashmap dos valores? Caso contrário,  quando seria o momento pra fazer isso?

**Comment by laercioag** [comment]
Jardeson me falou que quem faz isso é o Jasmin, até porquê no listener é só analise semântica.

**Comment by laercioag** [comment]
Era essa a dúvida? rs
